services:
  car_recognizer_sender_full_frame:
    environment:
      API_TOKEN: 
      SEND_INTERVAL_MINUTE: 5
      TIMEZONE: Etc/GMT-6
      PATH_FOLDER: /full_frame
      API_URL: http://195.49.212.96:9099/api/v2/orange/picture_upload
      SERVER_REQUEST_TIMEOUT: 10
    image: docker.io/nofantasyno/sender_full_picture:latest
    privileged: true
    restart: always
    volumes:
    - /media/usb/module/logs:/logs
    - /media/usb/module/full_frame:/full_frame
version: '3.4'
